config:
    DATA_DIR: "data/main_caption_data/"
    CAPTION_DATA_DIR: "data/main_caption_data/"
    CAPTION_FILE: "data/main_caption_data/Flickr8k_token_processed_flat.csv"
    IMAGE_ID_FILE_TRAIN: "data/main_caption_data/Flickr_8k.trainImages.txt"
    IMAGE_DATA_DIR: "data/flickr_data/Flickr_Data/Images/"
    MODEL_DIR: "model/"
    DEV_MODE: False
    BATCH_SIZE: 64
    VOCAB_THRESHOLD: 5
    # dimensionality of image embedding 
    IMG_EMBED_SIZE: 300
    # word embedding size
    WORD_EMBED_SIZE: 300
    # number of features in hidden state of the RNN decoder
    HIDDEN_SIZE: 512
    NUM_EPOCHS: 3
    # determines frequency of saving model weights
    SAVE_EVERY: 1
    PRINT_EVERY: 5
    VERBOSE: True
    VOCAB_FILE: "output/vocab.pkl"
    VOCAB_FROM_FILE: False

