config:
    DATA_DIR: "data/main_caption_data/"
    CAPTION_DATA_DIR: "data/main_caption_data/"
    CAPTION_FILE: "data/main_caption_data/Flickr8k_token_processed_small_caption_flat.csv"
    IMAGE_ID_FILE_TRAIN: "data/main_caption_data/Flickr_8k.trainImages.txt"
    IMAGE_ID_FILE_VAL: "data/main_caption_data/Flickr_8k.devImages.txt"
    IMAGE_ID_FILE_TEST: "data/main_caption_data/Flickr_8k.testImages.txt"
    IMAGE_DATA_DIR: "data/images/"
    MODEL_DIR: "model/"
    DEV_MODE: False
    BATCH_SIZE: 64
    VOCAB_THRESHOLD: 5
    # dimensionality of image embedding 
    IMG_EMBED_SIZE: 300
    # word embedding size
    WORD_EMBED_SIZE: 300
    # number of features in hidden state of the RNN decoder
    HIDDEN_SIZE: 512
    NUM_EPOCHS: 5
    # determines frequency of saving model weights
    SAVE_EVERY: 1
    PRINT_EVERY: 5
    VERBOSE: True
    VOCAB_FILE: "output/vocab.pkl"
    VOCAB_FROM_FILE: False
    DEV_MODE: False

